### ISSUE TITLE
dependency hell...

### ISSUE THREAD

**Issue by nallion** [arma7x/svelte-telekram#1]
Please, can you run "npm run build", zip and share "public" folder?
When i try make it on my pc, i receive many errors...

`(!) Plugin svelte: Home has unused export property 'location'. If it is for external reference only, please consider using `export const location`
src/routes/Home.svelte
16: import 'QRCode';
17: const navClass = 'homeNav';
18: export let location;
               ^
19: export let navigate;
20: export let getAppProp;
(!) Plugin svelte: Home has unused export property 'navigate'. If it is for external reference only, please consider using `export const navigate`
src/routes/Home.svelte
17: const navClass = 'homeNav';
18: export let location;
19: export let navigate;
               ^
20: export let getAppProp;
21: let dialog;
(!) Plugin svelte: Room has unused export property 'location'. If it is for external reference only, please consider using `export const location`
src/routes/Room.svelte
2: import { createKaiNavigator } from '../utils/navigation';
3: import { onMount, onDestroy } from 'svelte';
4: export let location;
              ^
5: export let navigate;
6: export let getAppProp;
(!) Plugin svelte: Room has unused export property 'navigate'. If it is for external reference only, please consider using `export const navigate`
src/routes/Room.svelte
3: import { onMount, onDestroy } from 'svelte';
4: export let location;
5: export let navigate;
              ^
6: export let getAppProp;
7: let name = 'Room';
(!) Unresolved dependencies
`

**Comment by arma7x** [comment]
Already run `npm install` ? Just ignore the yellow(warn)

**Comment by nallion** [comment]
> Already run `npm install` ? Just ignore the yellow(warn)

Yes, run it. But it not helpful. I receive 2 errors when i run npm run build

(!) Plugin svelte: Home has unused export property 'location'. If it is for external reference only, please consider using `export const location`
(!) Plugin svelte: Home has unused export property 'navigate'. If it is for external reference only, please consider using `export const navigate

When i test it in browser it no have result

![screenshot](https://user-images.githubusercontent.com/97355641/177475163-395449cf-c525-4998-aea5-691aca1c365e.png)

**Comment by cyan-2048** [comment]
if you have actually tried developing with svelte, unused exports will show up a lot if you haven't finished the app... it's not really the issue here

**Comment by arma7x** [comment]
> > Already run `npm install` ? Just ignore the yellow(warn)
> 
> Yes, run it. But it not helpful. I receive 2 errors when i run npm run build
> 
> (!) Plugin svelte: Home has unused export property 'location'. If it is for external reference only, please consider using `export const location` (!) Plugin svelte: Home has unused export property 'navigate'. If it is for external reference only, please consider using `export const navigate
> 
> When i test it in browser it no have result
> 
> ![screenshot](https://user-images.githubusercontent.com/97355641/177475163-395449cf-c525-4998-aea5-691aca1c365e.png)

http://localhost:5000/index.html

**Comment by cyan-2048** [comment]
alright so testing it myself, I get 2 missing dependencies
- @babel/runtime
- big-integer

building the app shows a blank screen, same as the image sent by OP

**Comment by arma7x** [comment]
@nallion http://localhost:5000/index.html

**Comment by cyan-2048** [comment]
> @nallion http://localhost:5000/index.html

this works!

**Comment by cyan-2048** [comment]
![image](https://user-images.githubusercontent.com/72785466/177482177-7c0ad3c6-0bb5-4560-a401-147872c80bf2.png)

add @babel/runtime to devDependencies 
and big-integer to dependencies

also, you should just use cjs or mjs for qrcode.js

**Comment by arma7x** [comment]
@cyan-2048  http://davidshimjs.github.io/qrcodejs/ ? Why @babel/runtime ?

**Comment by arma7x** [comment]
@cyan-2048  http://davidshimjs.github.io/qrcodejs/ ? Why @babel/runtime ?

**Comment by cyan-2048** [comment]
> @cyan-2048 http://davidshimjs.github.io/qrcodejs/ ? Why @babel/runtime ?

in rollup config file you use plugin @babel/plugin-transform-runtime?

**Comment by cyan-2048** [comment]
![image](https://user-images.githubusercontent.com/72785466/177484610-9f237c35-36de-4e54-ad6c-5ad6038ef447.png)

https://babeljs.io/docs/en/babel-plugin-transform-runtime
you are missing the dependency @babel/runtime

**Comment by cyan-2048** [comment]
says here it needs the runtime to be in production dependency, but you only use this for bundling, and your app is not a library so i guess it is not necessary....

**Comment by arma7x** [comment]
> add @babel/runtime to devDependencies and big-integer to dependencies
> 
> also, you should just use cjs or mjs for qrcode.js

both dependencies added. How to use cjs or mjs for qrcode.js ?

**Comment by cyan-2048** [comment]
> > add @babel/runtime to devDependencies and big-integer to dependencies
> > also, you should just use cjs or mjs for qrcode.js
> 
> both dependencies added. How to use cjs or mjs for qrcode.js ?

hmmm i take that back, it seems like qrcode.js uses non strict JS, maybe it would be better to actually find a better alternative, preferably one that allows you to use a canvas instead of using an image element... qrcodejs uses canvas and then generates datauri which is slow...

**Comment by nallion** [comment]
thank you. all works fine.
