### ISSUE TITLE
Please add prebuild release

### ISSUE THREAD

**Issue by Lolaify** [arma7x/svelte-telekram#10]
Hey, thanks for making this app! I was really happy when I found it but when executing `npm run build` I get this error:

```
PS C:\Users\kaleresan\Desktop\svelte-telekram-master> npm run build
> svelte-telekram@0.1.0 build C:\Users\kaleresan\Desktop\svelte-telekram-master
> rollup -c

Der Befehl "rollup" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-telekram@0.1.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-telekram@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
```

After a bit of troubleshooting I'm fairly certain that this is a problem with my environment. But I really don't want to have to learn what rollup is and how to fix it just to build this app. 
Could you add a prebuild release?
Thank you very much

**Comment by arma7x** [comment]
run `npm install`

**Comment by arma7x** [comment]
this is the latest build https://github.com/arma7x/svelte-telekram/blob/master/build_1669719353720.zip

**Comment by Lolaify** [comment]
It works! Thank you so much
