### ISSUE TITLE
Blank screen after asking for camera permissions

### ISSUE THREAD

**Issue by Daleth50** [arma7x/svelte-telekram#13]
I cloned the repo, set my own API key, build the app and side load it to the phone however i get a blank screen after giving camera permissions.

On paleMoon WebIDE i get this messages on the console

![imagen](https://github.com/arma7x/svelte-telekram/assets/40252320/a3880503-64ad-41a7-bf5c-a9b88d017f18)

I'm trying on a nokia 6300 4g on KaiOs 2.5.4

**Comment by arma7x** [comment]
The logs showing any errors. I also can't reproduce the erro on my Nokia 8110 4G. Everything up-to-date, I can re-build and deploy the app to my device. Maybe you can restart the device.

**Comment by Daleth50** [comment]
i tried to restart but no luck, im using node v16.20.0 to compile. should i use an specific version?

**Comment by arma7x** [comment]
Uninstall and please use my zip, https://github.com/arma7x/svelte-telekram/blob/master/build_1685163402334.zip

**DO NOT LOGIN**

**Comment by Daleth50** [comment]
ok so that build did work, so seems like is a problem at build the app on my computer. Which node version did you use?

**Comment by arma7x** [comment]
v18.16.0

Please follow the setup carefully https://github.com/arma7x/svelte-telekram/issues/2

**Comment by Daleth50** [comment]
ok so cloning the repo again and  build using node v18.16.0  seems to fix the issue. Thank you very much.

**Comment by mayaschroedl** [comment]
Hi, I have exactly the same problem on my Nokia 800 Tough. Could you please put the zip file online again? Thanks a lot
