### ISSUE TITLE
Unable to chat with contact

### ISSUE THREAD

**Issue by nallion** [arma7x/svelte-telekram#3]
Helllo, arma7x! 
I need to switch from old outdated legacy telekram to this new telekram-svetle. But i cannot chat with user, because send messages not implemented( What is your milestone? Can you implement send messages asap, and users switch to new client?

**Comment by arma7x** [comment]
No ETA, but I will finish it ASAP

**Comment by arma7x** [comment]
First, lets me implement **sendMessage** method on the current private and group chat list. Next, I will implement a method to fetch the contact list so users can start a new chat with their contact. 
But only for send text messages, no reply or forward

**Comment by arma7x** [comment]
@nallion Contacts now available. Click Menu > Contacts, you can click Chat on any contact list and the chat box will appear to begin a conversation, once the message was sent, the app will navigate to chat screen, you can press backkey to cancel. 

Searching still in progress and this is still in test mode

**Comment by arma7x** [comment]
@nallion Which kaios device are you using?

**Comment by nallion** [comment]
> @nallion Which kaios device are you using?

Nokia 8000 DS 4g
rooted with disable lowmemorykiller

**Comment by arma7x** [comment]
please test and give feedback

**Comment by nallion** [comment]
all works fine
after install application on login page phone freezes two times, on second time i need to remove and insert battery.
after this i sucessfull receive code & login to my account
can you plan to add handlng images?

**Comment by arma7x** [comment]
MTProto2 run very slow on KaiOS, I will handle authentication inside webworker
