### ISSUE TITLE
Problems I found (maybe it's my fault idk)

### ISSUE THREAD

**Issue by ludovicoivaldi** [arma7x/svelte-telekram#4]
Hello,
Let me say I'm really glad for your work with kaios apps.
I'm having a couple of problem with svelte-telekram: fist of all I had to install all the libraries on my computer but I think it was supposed to use the folders you put on \node_modules (that I'm not sure about).
Also I did not understand all the API thing at first because I didn't see the issue you put; if you could write it in the main page I would appreciate a lot.
Sorry for the terrible english, I'm italian ahahahah.
Hope this message helped you a little.
Best regards

Ludovico Ivaldi

**Comment by arma7x** [comment]
1. Duplicate & rename this file https://github.com/arma7x/svelte-telekram/blob/master/src/telegram_key_sample.ts to **telegram_key.ts**
2. Visit https://my.telegram.org/auth to get your **app_id** and **api_hash**
3. Update **telegram_key.ts** configuration by using your own **app_id** and **api_hash**
4. Finally, install dependencies via **yarn install** or **npm install**

**Comment by arma7x** [comment]
@ludovicoivaldi https://anonymfile.com/8Lbz/telekram.zip

**Comment by ludovicoivaldi** [comment]
Thank you so much!!! 😍
