### ISSUE TITLE
app launches stuck at a white screen

### ISSUE THREAD

**Issue by zoelilylain** [arma7x/svelte-telekram#5]
no changes made beyond api key
git cloned from master branch on Friday, September 30th, 2022 at 17:39 (5:39 pm) EST
npm install with no issues
built successfully
KaiOS 2.5.4
AT&T Cingular Flex, Jailbroken, not rooted

app starts at a white screen and stays there. initial launch asked for camera permission and to select which camera to use (I only have rear so its the only option)

**Comment by arma7x** [comment]
I can't reproduce the bug on my Nokia 8110 4G. However, I have commit an update to improve app performance, please pull and rebuild the app

**Comment by zoelilylain** [comment]
App launches correctly now, although my number got banned out of nowhere about a day later lmao. sent an email to support but they still havent responded.

**Comment by zoelilylain** [comment]
I'm actually thinking it was my (at the time) fucked up outdated linux install causing isues, but for all either of us know it could have been cosmic bit flip
