### ISSUE TITLE
Would like to send files :)

### ISSUE THREAD

**Issue by unleterd** [arma7x/svelte-telekram#6]

**Comment by arma7x** [comment]
on my todo list

**Comment by no382001** [comment]
hi, do you have any plans of implementing this in the near future? if not, id like to try my hands on it

**Comment by arma7x** [comment]
Nope, I'm not using KaiOS as my main phone anymore

**Comment by no382001** [comment]
I have a working implementation on my fork which i have used for some time. Is this feature completely abandoned?

**Comment by arma7x** [comment]
> I have a working implementation on my fork which i have used for some time. Is this feature completely abandoned?
yes
