### ISSUE TITLE
Telegram account is banned on KaiOS device

### ISSUE THREAD

**Issue by unleterd** [arma7x/svelte-telekram#7]
When I logged in my telegram account in web brower with this svelte-telekram client, everything works fine.
Then I logged in with packaged app of this svelte-telekram client on **KaiOS device** for just one time, my account was banned.
I send recover request to recover@telegram.org and https://telegram.org/support, no response yet.

Anyone get any ideas? 
Thanks!

**Comment by arma7x** [comment]
telegram usually bans voip numbers. you can email their support to unban
