### ISSUE TITLE
Stuck at connecting...

### ISSUE THREAD

**Issue by AubergineOfTheMoon** [arma7x/svelte-telekram#9]
Device, Nokia 2780 flip, KaiOS 3.1

I followed the steps to use my own APP_ID and hash
Removed the KaiOS 2.x manifest
Added an ID to the 3.x manifest
Used the build.sh
Installed the zip by uploading through dev portal

Typing in my phone number, then clicking send code seemingly does nothing
Neither does clicking log in via QR code

**Comment by AubergineOfTheMoon** [comment]
The exit button does work for what it's worth

**Comment by arma7x** [comment]
The client might not work on KaiOS 3.1 and I don't have any KaiOS 3.1 device to debug the error

**Comment by arma7x** [comment]
I will debug the client on simulator and fix the error ASAP

**Comment by arma7x** [comment]
The bug related to 'Content Security Policy', only affect KaiOS 3.x

```
const blob = new Blob(['js script here'], {type: 'application/javascript'});
const worker = new Worker(URL.createObjectURL(blob));
```

I will fix the bug

**Comment by arma7x** [comment]
Solve, https://github.com/arma7x/svelte-telekram/commit/aee92299375f3c785ea3dc089e902e0ccb4cd79c

I'm using KaiOS v3 Simulator and able to login into my telegram account
